#nullable enable
// Tech-spec 02 § WaveEvent. One entry of a WaveDefinition.events array.

using System;

namespace Brave.Gameplay.Definitions
{
    public enum WaveEventType { Spawn, MiniBoss, Boss, Lull }
    public enum SpawnPattern  { Ring, Arc, RandomEdge, ScriptedPoints, Stream, Scatter }

    /// <summary>
    /// A single timed wave event. The level-designer authors these as JSON; the SO is
    /// generated by the balance tool. Gameplay-engineer's <c>WaveSpawner</c> consumes them.
    /// </summary>
    [Serializable]
    public struct WaveSpawnEntry
    {
        public float triggerMinute;       // 0..10+ (run is 7-10 minutes; boss approach at 7:00, boss at 8:00)
        public WaveEventType type;
        public EnemyDefinition? enemy;    // for Spawn / MiniBoss
        public int spawnCount;
        public SpawnPattern pattern;
        public float radius;              // world units for ring/arc/stream patterns
    }
}
