#if UNITY_EDITOR
// One-shot scene generator — creates the minimum-viable scenes the PlayMode
// tests expect (Boot, Run, PerfStress) and registers them in EditorBuildSettings.
// Run via menu: Brave > Scaffold Phase-5 Scenes.
//
// Wave 6 (make-it-playable): EnsureRun() now wires the full gameplay loop:
//   WaveSpawner, AutoAttackController, CarrotProjectilePool,
//   RunTimer, RunController, RunHudController + UIDocument.
// The ForceScaffoldRun() entry point also backs up and deletes Run.unity before
// regenerating, so the scene grows from ~773 lines to 1500+.

using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

using Brave.Gameplay.Definitions;   // gameplay-engineer Wave 2: PlayerMover wiring needs CharacterDefinition
using Brave.Gameplay.Movement;
using Brave.Gameplay.Combat;        // Wave 13: CarrotProjectilePool, Projectile prefab wiring
using Brave.Gameplay.Run;           // Wave 13: CameraFollow wiring on MainCamera
using Brave.Gameplay.MVP;           // Wave 13: MvpWaveSpawner runtime fallback (no SO needed)
using Brave.Boot.Editor;            // BalanceJsonImporter — generates SOs before scene wiring

public static class SceneSetup
{
    private const string SceneDir = "Assets/_Brave/Scenes";

    // Run-scene wiring inputs (gameplay-engineer Wave 2). Const string lives here so the
    // AssetDatabase lookup has no per-frame allocation and is easy to grep when assets move.
    private const string CharBunnyAssetPath     = "Assets/_Brave/Data/Balance/Char_bunny.asset";

    // Wave 6 wiring asset paths. All are generated by BalanceJsonImporter.GenerateAll().
    // If missing, the wiring slot is left null with a logged warning (graceful degradation).
    private const string WeaponCarrotAssetPath   = "Assets/_Brave/Data/Balance/Weapon_carrot-boomerang.asset";
    private const string WeaponPebbleAssetPath   = "Assets/_Brave/Data/Balance/Weapon_pebble-sling.asset";
    private const string RunHudUxmlPath          = "Assets/_Brave/UI/Documents/RunHud.uxml";

    [MenuItem("Brave/Scaffold Phase-5 Scenes")]
    public static void Scaffold()
    {
        Directory.CreateDirectory(SceneDir);

        EnsureBoot();
        EnsureMainMenu();
        EnsureLoadout();
        EnsureRun();
        EnsurePerfStress();
        RegisterInBuildSettings();

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("[SceneSetup] OK — Boot/Run/PerfStress scenes scaffolded and registered.");
    }

    /// <summary>
    /// Crash-fix (#1) entry — deletes pre-existing empty scaffold scenes
    /// (Boot, MainMenu, Loadout, PerfStress) BEFORE running the regular Scaffold flow,
    /// so the EnsureX methods rebuild them from scratch with their full GameObject set.
    /// Run.unity is preserved (it has real authored content — 24 YAML docs, full gameplay wiring).
    /// </summary>
    [MenuItem("Brave/Force-Scaffold Phase-5 Scenes (deletes Boot/MainMenu/Loadout/PerfStress)")]
    public static void ForceScaffold()
    {
        Directory.CreateDirectory(SceneDir);

        // Delete the empty placeholder scenes (and their .meta) so EnsureX runs fresh.
        // Run.unity is NEVER deleted — it has 24 YAML docs of real authored content.
        foreach (var sceneName in new[] { "Boot", "MainMenu", "Loadout", "PerfStress" })
        {
            var unity = $"{SceneDir}/{sceneName}.unity";
            var meta = $"{unity}.meta";
            if (File.Exists(unity))
            {
                File.Delete(unity);
                Debug.Log($"[SceneSetup] ForceScaffold deleted {unity}");
            }
            if (File.Exists(meta))
            {
                File.Delete(meta);
                Debug.Log($"[SceneSetup] ForceScaffold deleted {meta}");
            }
        }

        // Refresh so AssetDatabase forgets the old GUIDs before we recreate.
        AssetDatabase.Refresh();

        Scaffold();
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("[SceneSetup] ForceScaffold OK — scenes deleted and rebuilt with fresh GUIDs.");
    }

    /// <summary>
    /// Wave 6 (make-it-playable) entry — backs up and deletes Run.unity so EnsureRun()
    /// regenerates it with the full gameplay loop wired (WaveSpawner, AutoAttackController,
    /// CarrotProjectilePool, RunTimer, RunController, RunHudController).
    /// Leaves Boot/MainMenu/Loadout/PerfStress intact.
    /// </summary>
    [MenuItem("Brave/Force-Scaffold Run Scene (playable — backs up Run.unity first)")]
    public static void ForceScaffoldRun()
    {
        Directory.CreateDirectory(SceneDir);

        var runUnity = $"{SceneDir}/Run.unity";
        var runMeta  = $"{runUnity}.meta";

        // Backup Run.unity to /tmp before deletion.
        if (File.Exists(runUnity))
        {
            var ts = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            var backup = $"/tmp/run-unity-before-{ts}.unity";
            File.Copy(runUnity, backup, overwrite: true);
            Debug.Log($"[SceneSetup] ForceScaffoldRun backed up {runUnity} → {backup}");
            File.Delete(runUnity);
        }
        if (File.Exists(runMeta))
            File.Delete(runMeta);

        AssetDatabase.Refresh();

        // Re-run just the Run scene (all others unchanged).
        EnsureRun();
        RegisterInBuildSettings();

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("[SceneSetup] ForceScaffoldRun OK — Run.unity rebuilt with gameplay loop.");
    }

    /// <summary>CLI entry for headless invocation.</summary>
    public static void RunHeadless()
    {
        Scaffold();
        EditorApplication.Exit(0);
    }

    /// <summary>
    /// CLI entry for headless force-scaffold — used by crash-fix (#1) batch invocation
    /// to regenerate Boot/MainMenu/Loadout/PerfStress from scratch.
    /// </summary>
    public static void RunHeadlessForce()
    {
        ForceScaffold();
        EditorApplication.Exit(0);
    }

    /// <summary>
    /// Wave 6 CLI entry — generates balance SOs first, then force-rebuilds Run.unity
    /// with the full playable gameplay loop. Use from the batchmode command line:
    ///   -executeMethod SceneSetup.RunHeadlessForce
    /// Note: This replaces the previous RunHeadlessForce contract for the make-it-playable
    /// wave. The old RunHeadlessForce (Boot/Menu/Loadout/Perf only) is preserved above.
    /// </summary>
    public static void RunHeadlessPlayable()
    {
        // Step 1: generate balance SOs from JSON so asset paths resolve during EnsureRun.
        BalanceJsonImporter.GenerateAll();
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        // Step 2: rebuild Run scene with gameplay wiring.
        ForceScaffoldRun();
        EditorApplication.Exit(0);
    }

    // -------------------------------------------------------------------------
    // Wave 13 — Playable MVP Run wiring.
    //
    // Why a separate menu / entry: the canonical EnsureRun() above leaves the
    // Run scene functional but inert — projectilePrefab is null on the pool,
    // WaveSpawner has no WaveDefinition SO, MainCamera has no CameraFollow.
    // EnsurePlayableMvpRun() patches the live Run.unity in place so it actually
    // plays end-to-end without authoring assets first. Idempotent.
    //
    //   * Creates Assets/_Brave/Art/Prefabs/CarrotProjectile.prefab if missing
    //     (0.2u cube, orange URP/Lit).
    //   * Wires that prefab onto the CarrotProjectilePool component.
    //   * Adds Rigidbody (non-kinematic, freezeRotation) to Player.
    //   * Adds CameraFollow to MainCamera with target = Player.transform.
    //   * Replaces the inert canonical WaveSpawner setup with an MvpWaveSpawner
    //     that spawns 5 swarmers on a ring of r=8 every 3 s (no SO required).
    //   * Idempotent on all of the above — re-running is a no-op when wiring
    //     is already correct.
    // -------------------------------------------------------------------------

    private const string CarrotProjectilePrefabPath = "Assets/_Brave/Art/Prefabs/CarrotProjectile.prefab";
    private const string PrefabsDir = "Assets/_Brave/Art/Prefabs";
    private const string ArtRoot = "Assets/_Brave/Art";

    [MenuItem("BraveBunny/MVP/Ensure Playable Run Scene")]
    public static void EnsurePlayableMvpRun()
    {
        Directory.CreateDirectory(SceneDir);

        // Step 0 — generate balance SOs if they're missing. Cheap when up-to-date.
        // BalanceJsonImporter.GenerateAll();

        // Step 1 — ensure the procedural CarrotProjectile prefab exists.
        var projectilePrefab = EnsureCarrotProjectilePrefab();

        var runPath = $"{SceneDir}/Run.unity";
        var scene = File.Exists(runPath)
            ? EditorSceneManager.OpenScene(runPath, OpenSceneMode.Single)
            : EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        // Step 2 — resolve / create Player.
        var player = GameObject.Find("Player");
        if (player == null)
        {
            player = GameObject.CreatePrimitive(PrimitiveType.Cube);
            player.name = "Player";
            player.tag = "Player";
            player.transform.position = Vector3.zero;
        }
        WirePlayerComponents(player);

        // Step 3 — resolve / create MainCamera, attach CameraFollow.
        var cam = Camera.main != null ? Camera.main.gameObject : GameObject.Find("MainCamera");
        if (cam == null)
        {
            cam = new GameObject("MainCamera");
            var camera = cam.AddComponent<Camera>();
            camera.fieldOfView = 35;
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = new Color(0.74f, 0.88f, 0.45f);
            cam.tag = "MainCamera";
            cam.AddComponent<AudioListener>();
            cam.transform.position = new Vector3(0, 14.7f, -10.4f);
            cam.transform.rotation = Quaternion.Euler(55, 0, 0);
        }
        WireCameraFollow(cam, player.transform);

        // Step 4 — Directional light (skip if any Light already in scene).
        EnsureDirectionalLight();

        // Step 5 — Ensure ground plane (the existing MeadowGround is fine; create a Quad
        // fallback if no ground is present).
        EnsureGround();

        // Step 6 — Resolve / create the CarrotProjectilePool with prefab assigned.
        var pool = EnsureCarrotPoolWired(projectilePrefab);

        // Step 7 — Resolve / create the AutoAttackController on Player + wire pool.
        WireAutoAttackController(player, pool);

        // Step 8 — Resolve / create the MvpWaveSpawner (replaces inert canonical spawner).
        EnsureMvpWaveSpawner(player.transform);

        // Step 9 — RunController + RunTimer remain as-is from EnsureRun(); confirm they exist.
        EnsureRunControllerIfMissing();

        // Step 10 — HUD remains as-is. UXML element names verified against RunHudController
        // queries (HpFill/XpFill/etc.) — all present in Assets/_Brave/UI/Documents/RunHud.uxml.

        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene, runPath);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("[SceneSetup] EnsurePlayableMvpRun OK — Run scene patched for MVP playability.");
    }

    /// <summary>CLI entry: -executeMethod SceneSetup.EnsurePlayableMvpRunHeadless.</summary>
    public static void EnsurePlayableMvpRunHeadless()
    {
        try
        {
            EnsurePlayableMvpRun();
            EditorApplication.Exit(0);
        }
        catch (Exception ex)
        {
            Debug.LogError($"[SceneSetup] EnsurePlayableMvpRunHeadless failed: {ex}");
            EditorApplication.Exit(1);
        }
    }

    private static GameObject EnsureCarrotProjectilePrefab()
    {
        var existing = AssetDatabase.LoadAssetAtPath<GameObject>(CarrotProjectilePrefabPath);
        if (existing != null) return existing;

        if (!Directory.Exists(ArtRoot)) Directory.CreateDirectory(ArtRoot);
        if (!Directory.Exists(PrefabsDir)) Directory.CreateDirectory(PrefabsDir);

        // Build a tiny 0.2u cube tinted carrot-orange. URP/Lit shader; fall back to Standard.
        var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
        go.name = "CarrotProjectile";
        go.transform.localScale = new Vector3(0.2f, 0.2f, 0.2f);

        var renderer = go.GetComponent<MeshRenderer>();
        if (renderer != null)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            var mat = new Material(shader) { color = new Color(1f, 0.55f, 0.15f) };
            renderer.sharedMaterial = mat;
        }

        // The runtime collider isn't strictly required (Projectile uses EnemyRegistry,
        // not Unity colliders), but having one helps if a future hit-detector wants it.
        // The default BoxCollider added by CreatePrimitive is fine.

        // Add the Projectile component so spawned instances are actually projectiles.
        go.AddComponent<Projectile>();

        var prefab = PrefabUtility.SaveAsPrefabAsset(go, CarrotProjectilePrefabPath);
        GameObject.DestroyImmediate(go);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log($"[SceneSetup] Created procedural carrot projectile prefab at {CarrotProjectilePrefabPath}.");
        return prefab!;
    }

    private static void WirePlayerComponents(GameObject player)
    {
        // PlayerMover is wired via EnsureRunPlayerWiring (canonical path); call it for safety.
        EnsureRunPlayerWiring(player);

        // MeshRenderer + URP material (replace any missing).
        if (player.GetComponent<MeshFilter>() == null)
            player.AddComponent<MeshFilter>().sharedMesh = Resources.GetBuiltinResource<Mesh>("Cube.fbx");
        var pr = player.GetComponent<MeshRenderer>();
        if (pr == null) pr = player.AddComponent<MeshRenderer>();
        if (pr.sharedMaterial == null || pr.sharedMaterial.shader == null)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            pr.sharedMaterial = new Material(shader) { color = new Color(0.83f, 0.64f, 0.45f) }; // bunny-brown #d4a373
        }

        // Replace BoxCollider with CapsuleCollider for cleaner rolling on the ground.
        var box = player.GetComponent<BoxCollider>();
        if (box != null) GameObject.DestroyImmediate(box);
        var cap = player.GetComponent<CapsuleCollider>();
        if (cap == null) cap = player.AddComponent<CapsuleCollider>();
        cap.radius = 0.4f;
        cap.height = 1.0f;
        cap.direction = 1; // Y axis

        // Rigidbody — non-kinematic, freeze rotation, gravity off so the bunny stays on
        // the ground without needing a NavMesh or kinematic-character-controller pass.
        var rb = player.GetComponent<Rigidbody>();
        if (rb == null) rb = player.AddComponent<Rigidbody>();
        rb.useGravity = false;
        rb.isKinematic = false;
        rb.constraints = RigidbodyConstraints.FreezeRotation | RigidbodyConstraints.FreezePositionY;
        rb.linearDamping = 4f;
    }

    private static void WireCameraFollow(GameObject cam, Transform target)
    {
        var follow = cam.GetComponent<CameraFollow>();
        if (follow == null) follow = cam.AddComponent<CameraFollow>();
        var so = new SerializedObject(follow);
        var targetProp = so.FindProperty("target");
        if (targetProp != null) targetProp.objectReferenceValue = target;
        var offsetProp = so.FindProperty("offset");
        if (offsetProp != null) offsetProp.vector3Value = new Vector3(10f, 12f, -8f);
        var lookProp = so.FindProperty("lookAtTarget");
        if (lookProp != null) lookProp.boolValue = true;
        so.ApplyModifiedPropertiesWithoutUndo();
        // Pre-position the camera at the resolved offset so the first frame doesn't drift.
        cam.transform.position = target.position + new Vector3(10f, 12f, -8f);
        cam.transform.LookAt(target.position);
    }

    private static void EnsureDirectionalLight()
    {
        var existing = UnityEngine.Object.FindFirstObjectByType<Light>();
        if (existing != null && existing.type == LightType.Directional) return;
        var go = new GameObject("DirectionalLight");
        var l = go.AddComponent<Light>();
        l.type = LightType.Directional;
        l.intensity = 1.2f;
        l.color = new Color(1f, 0.96f, 0.85f);
        go.transform.rotation = Quaternion.Euler(50, -30, 0);
    }

    private static void EnsureGround()
    {
        // Re-use the existing MeadowGround Plane if present.
        if (GameObject.Find("MeadowGround") != null) return;
        if (GameObject.Find("Ground") != null) return;

        var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
        ground.name = "MeadowGround";
        ground.transform.localScale = new Vector3(8, 1, 8);
        ground.transform.position = new Vector3(0, -0.5f, 0);
        var gr = ground.GetComponent<Renderer>();
        if (gr != null)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            gr.sharedMaterial = new Material(shader) { color = new Color(0.65f, 0.84f, 0.37f) };
        }
    }

    private static CarrotProjectilePool EnsureCarrotPoolWired(GameObject prefabAsset)
    {
        var go = GameObject.Find("[CarrotProjectilePool]");
        if (go == null) go = new GameObject("[CarrotProjectilePool]");
        var pool = go.GetComponent<CarrotProjectilePool>();
        if (pool == null) pool = go.AddComponent<CarrotProjectilePool>();

        var so = new SerializedObject(pool);
        var prefabProp = so.FindProperty("projectilePrefab");
        if (prefabProp != null && prefabAsset != null)
        {
            // The serialized field is typed as Projectile (component). Look up the
            // Projectile MonoBehaviour on the prefab asset and assign that.
            var proj = prefabAsset.GetComponent<Projectile>();
            if (proj != null)
                prefabProp.objectReferenceValue = proj;
        }
        so.ApplyModifiedPropertiesWithoutUndo();
        return pool;
    }

    private static void WireAutoAttackController(GameObject player, CarrotProjectilePool pool)
    {
        var aa = player.GetComponent<AutoAttackController>();
        if (aa == null) aa = player.AddComponent<AutoAttackController>();
        var so = new SerializedObject(aa);

        var mover = player.GetComponent<PlayerMover>();
        var playerProp = so.FindProperty("player");
        if (playerProp != null && mover != null && playerProp.objectReferenceValue == null)
            playerProp.objectReferenceValue = mover;

        var poolProp = so.FindProperty("projectilePool");
        if (poolProp != null) poolProp.objectReferenceValue = pool;

        var weaponProp = so.FindProperty("weapon");
        if (weaponProp != null && weaponProp.objectReferenceValue == null)
        {
            var weaponDef = AssetDatabase.LoadAssetAtPath<WeaponDefinition>(WeaponCarrotAssetPath)
                ?? AssetDatabase.LoadAssetAtPath<WeaponDefinition>(WeaponPebbleAssetPath);
            if (weaponDef != null) weaponProp.objectReferenceValue = weaponDef;
        }
        so.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void EnsureMvpWaveSpawner(Transform hero)
    {
        var go = GameObject.Find("[MvpWaveSpawner]");
        if (go == null) go = new GameObject("[MvpWaveSpawner]");
        var spawner = go.GetComponent<MvpWaveSpawner>();
        if (spawner == null) spawner = go.AddComponent<MvpWaveSpawner>();
        // Configure via SerializedObject so the values persist on the scene asset.
        var so = new SerializedObject(spawner);
        SetFloat(so, "spawnIntervalSeconds", 3f);
        SetInt(so, "swarmersPerWave", 5);
        SetFloat(so, "ringRadius", 8f);
        SetInt(so, "activeCap", 50);
        SetFloat(so, "swarmerMoveSpeed", 2.5f);
        SetFloat(so, "swarmerHp", 10f);

        var heroProp = so.FindProperty("hero");
        if (heroProp != null) heroProp.objectReferenceValue = hero;
        so.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void EnsureRunControllerIfMissing()
    {
        var existing = GameObject.Find("[Run]");
        if (existing != null) return;
        var timerGo = GameObject.Find("[RunTimer]") ?? new GameObject("[RunTimer]");
        var timerType = FindType("Brave.Gameplay.Run.RunTimer");
        if (timerType != null && timerGo.GetComponent(timerType) == null)
            timerGo.AddComponent(timerType);
        EnsureRunController(timerGo);
    }

    private static void SetFloat(SerializedObject so, string field, float value)
    {
        var p = so.FindProperty(field);
        if (p != null) p.floatValue = value;
    }

    private static void SetInt(SerializedObject so, string field, int value)
    {
        var p = so.FindProperty(field);
        if (p != null) p.intValue = value;
    }

    private static void EnsureBoot()
    {
        var path = $"{SceneDir}/Boot.unity";
        if (File.Exists(path)) { Debug.Log("[SceneSetup] Boot.unity already exists, skipping"); return; }

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        // MainCamera + AudioListener so the very first iOS frame renders something
        // (bunny-cream clear) instead of black. Black-frame-on-launch is the symptom that
        // looks like a crash to iOS WatchDog if no transition follows (see GH issue #1).
        var cam = new GameObject("MainCamera");
        var camera = cam.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = new Color(1f, 0.92f, 0.76f); // bunny-cream
        cam.tag = "MainCamera";
        cam.AddComponent<AudioListener>();

        // [Bootstrap] root GameObject — hosts GameContextBootstrap.
        var bootstrap = new GameObject("[Bootstrap]");

        var bootstrapType = FindType("Brave.Systems.Context.GameContextBootstrap");
        if (bootstrapType != null)
        {
            bootstrap.AddComponent(bootstrapType);
        }
        else
        {
            Debug.LogWarning("[SceneSetup] GameContextBootstrap type not resolved — Boot scene shipped without it.");
        }

        // [SceneFlow] sibling — listens for Bootstrapper.GameContextReady and loads Run.
        var sceneFlow = new GameObject("[SceneFlow]");
        var sceneFlowType = FindType("Brave.Systems.Context.SceneFlow");
        if (sceneFlowType != null)
        {
            sceneFlow.AddComponent(sceneFlowType);
        }
        else
        {
            Debug.LogWarning("[SceneSetup] SceneFlow type not resolved — Boot scene will not transition.");
        }

        // EventSystem so UI input works on first run.
        var eventSystem = new GameObject("EventSystem");
        var esType = FindType("UnityEngine.EventSystems.EventSystem");
        if (esType != null) eventSystem.AddComponent(esType);

        EditorSceneManager.SaveScene(scene, path);
        Debug.Log($"[SceneSetup] created {path}");
    }

    private static void EnsureRun()
    {
        var path = $"{SceneDir}/Run.unity";
        if (File.Exists(path)) { Debug.Log("[SceneSetup] Run.unity already exists, skipping"); return; }

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        // Top-down 3/4 camera per art-bible 00-style-overview (FOV 35°, dist 18u).
        var cam = new GameObject("MainCamera");
        var camera = cam.AddComponent<Camera>();
        camera.fieldOfView = 35;
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = new Color(0.74f, 0.88f, 0.45f, 1f); // meadow-lime
        cam.transform.position = new Vector3(0, 14.7f, -10.4f);     // top-down 3/4
        cam.transform.rotation = Quaternion.Euler(55, 0, 0);
        cam.tag = "MainCamera";
        cam.AddComponent<AudioListener>();

        // Directional light approximating Meadow noon.
        var light = new GameObject("DirectionalLight");
        var l = light.AddComponent<Light>();
        l.type = LightType.Directional;
        l.intensity = 1.2f;
        l.color = new Color(1f, 0.96f, 0.85f);
        light.transform.rotation = Quaternion.Euler(50, -30, 0);

        // Placeholder "Player" — a primitive cube tinted bunny-cream so the
        // tests have something to assert on; replaced by the real character
        // prefab in a later wave.
        var player = GameObject.CreatePrimitive(PrimitiveType.Cube);
        player.name = "Player";
        player.tag = "Player";
        player.transform.position = Vector3.zero;
        var renderer = player.GetComponent<Renderer>();
        if (renderer != null)
        {
            var mat = new Material(Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard"));
            mat.color = new Color(1f, 0.92f, 0.76f); // bunny cream
            renderer.sharedMaterial = mat;
        }

        // Ground plane — Meadow.
        var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
        ground.name = "MeadowGround";
        ground.transform.localScale = new Vector3(8, 1, 8); // 80x80 game units
        ground.transform.position = new Vector3(0, -0.5f, 0);
        var gr = ground.GetComponent<Renderer>();
        if (gr != null)
        {
            var mat = new Material(Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard"));
            mat.color = new Color(0.65f, 0.84f, 0.37f); // meadow lime, slightly desaturated
            gr.sharedMaterial = mat;
        }

        // gameplay-engineer Wave 2 — wire PlayerMover + CharacterDefinition on the Player.
        // Kept inline here (not a separate Editor/PlayerWiring.cs) only to minimise the
        // diff; see ADR-0017 follow-up hand-off for the option of moving this out later.
        EnsureRunPlayerWiring(player);

        // Wave 6 (make-it-playable) — wire the full gameplay loop so the run scene
        // actually does something: enemies spawn, auto-attack fires, HUD shows state.
        var projectilePoolGO = EnsureRunCarrotProjectilePool();
        EnsureRunAutoAttack(player, projectilePoolGO);
        var runTimerGO = EnsureRunTimer();
        EnsureRunWaveSpawner(player, runTimerGO);
        EnsureRunController(runTimerGO);
        EnsureRunHud();

        // Wave 7A + 7B — juice services (hitstop / screenshake / damage numbers),
        // boss container, and modal UI controllers (pause / level-up draft /
        // run-end tally). All helpers are idempotent.
        RunSceneWiringSetup.WireRunScene();

        EditorSceneManager.SaveScene(scene, path);
        Debug.Log($"[SceneSetup] created {path}");
    }

    // -------------------------------------------------------------------------
    // Wave 6 helpers — each adds one logical system to the Run scene.
    // All helpers are idempotent: they check GetComponent before AddComponent.
    // Missing SO assets produce a LogWarning; the component is added un-configured
    // (graceful degradation matching EnsureRunPlayerWiring's contract).
    // -------------------------------------------------------------------------

    /// <summary>
    /// Creates [CarrotProjectilePool] GameObject and attaches CarrotProjectilePool component.
    /// The projectile prefab is not auto-assigned here (requires a real Prefab asset that
    /// doesn't exist yet); AutoAttack will log a warning and disable direct-cast at runtime.
    /// Returns the new GameObject so AutoAttackController can reference it.
    /// </summary>
    private static GameObject EnsureRunCarrotProjectilePool()
    {
        var go = new GameObject("[CarrotProjectilePool]");
        var poolType = FindType("Brave.Gameplay.Combat.CarrotProjectilePool");
        if (poolType == null)
        {
            Debug.LogWarning("[SceneSetup] CarrotProjectilePool type not found — pool GameObject added without component.");
            return go;
        }
        go.AddComponent(poolType);
        Debug.Log("[SceneSetup] [CarrotProjectilePool] wired.");
        return go;
    }

    /// <summary>
    /// Adds AutoAttackController to the Player GameObject and wires:
    ///   - player = PlayerMover on Player
    ///   - weapon = Weapon_carrot-boomerang.asset (fallback: Weapon_pebble-sling.asset)
    ///   - projectilePool = the [CarrotProjectilePool] component
    /// </summary>
    private static void EnsureRunAutoAttack(GameObject player, GameObject projectilePoolGO)
    {
        var aaType = FindType("Brave.Gameplay.Combat.AutoAttackController");
        if (aaType == null)
        {
            Debug.LogWarning("[SceneSetup] AutoAttackController type not found — skipping.");
            return;
        }

        var controller = player.GetComponent(aaType) ?? player.AddComponent(aaType);
        var so = new SerializedObject(controller);

        // Wire the PlayerMover reference.
        var mover = player.GetComponent<PlayerMover>();
        var playerProp = so.FindProperty("player");
        if (playerProp != null && mover != null)
            playerProp.objectReferenceValue = mover;

        // Resolve weapon SO — prefer carrot-boomerang (vertical slice); fall back to pebble-sling.
        WeaponDefinition? weaponDef =
            AssetDatabase.LoadAssetAtPath<WeaponDefinition>(WeaponCarrotAssetPath)
            ?? AssetDatabase.LoadAssetAtPath<WeaponDefinition>(WeaponPebbleAssetPath);
        if (weaponDef == null)
        {
            Debug.LogWarning(
                "[SceneSetup] No weapon SO found at carrot-boomerang or pebble-sling paths. "
                + "Run 'Brave > Generate Balance SOs from JSON' then re-run this scaffold. "
                + "AutoAttackController will disable its direct-cast path at runtime.");
        }
        var weaponProp = so.FindProperty("weapon");
        if (weaponProp != null)
            weaponProp.objectReferenceValue = weaponDef;

        // Wire the CarrotProjectilePool component.
        var poolType = FindType("Brave.Gameplay.Combat.CarrotProjectilePool");
        if (poolType != null && projectilePoolGO != null)
        {
            var poolComp = projectilePoolGO.GetComponent(poolType);
            var poolProp = so.FindProperty("projectilePool");
            if (poolProp != null && poolComp != null)
                poolProp.objectReferenceValue = poolComp;
        }

        so.ApplyModifiedPropertiesWithoutUndo();
        Debug.Log("[SceneSetup] AutoAttackController wired on Player.");
    }

    /// <summary>
    /// Creates [RunTimer] GameObject with a RunTimer component.
    /// Returns the GameObject so WaveSpawner and RunController can reference it.
    /// </summary>
    private static GameObject EnsureRunTimer()
    {
        var go = new GameObject("[RunTimer]");
        var timerType = FindType("Brave.Gameplay.Run.RunTimer");
        if (timerType == null)
        {
            Debug.LogWarning("[SceneSetup] RunTimer type not found — GameObject added without component.");
            return go;
        }
        go.AddComponent(timerType);
        Debug.Log("[SceneSetup] [RunTimer] wired.");
        return go;
    }

    /// <summary>
    /// Creates [WaveSpawner] GameObject with a WaveSpawner component. Wires:
    ///   - hero = Player transform
    ///   - runTimer = RunTimer component from <paramref name="runTimerGO"/>
    ///   - wave = null (no WaveDefinition SO exists yet — logged warning)
    /// </summary>
    private static void EnsureRunWaveSpawner(GameObject player, GameObject runTimerGO)
    {
        var spawnerType = FindType("Brave.Gameplay.Spawning.WaveSpawner");
        if (spawnerType == null)
        {
            Debug.LogWarning("[SceneSetup] WaveSpawner type not found — skipping.");
            return;
        }

        var go = new GameObject("[WaveSpawner]");
        var comp = go.AddComponent(spawnerType);
        var so = new SerializedObject(comp);

        // hero — the Player's Transform.
        var heroProp = so.FindProperty("hero");
        if (heroProp != null)
            heroProp.objectReferenceValue = player.transform;

        // runTimer — the RunTimer component on [RunTimer] GO.
        var timerType = FindType("Brave.Gameplay.Run.RunTimer");
        if (timerType != null && runTimerGO != null)
        {
            var timerComp = runTimerGO.GetComponent(timerType);
            var timerProp = so.FindProperty("runTimer");
            if (timerProp != null && timerComp != null)
                timerProp.objectReferenceValue = timerComp;
        }

        // wave — no WaveDefinition asset exists until level-designer generates them.
        var waveProp = so.FindProperty("wave");
        if (waveProp != null)
            waveProp.objectReferenceValue = null;   // graceful null — logged below

        Debug.LogWarning(
            "[SceneSetup] WaveSpawner.wave is null — no WaveDefinition SO found. "
            + "Generate Assets/_Brave/Data/Balance/Wave_meadow.asset from "
            + "docs/09-level-design/01-biomes/meadow/waves.json to enable spawning.");

        so.ApplyModifiedPropertiesWithoutUndo();
        Debug.Log("[SceneSetup] [WaveSpawner] wired (wave=null, hero+runTimer set).");
    }

    /// <summary>
    /// Creates [Run] GameObject with RunController, plus CharacterDefinition wiring.
    /// RunController also needs a RunTimer reference (injected at runtime via Initialise;
    /// the serialized _deathChannel is left null — graceful degradation).
    /// </summary>
    private static void EnsureRunController(GameObject runTimerGO)
    {
        var controllerType = FindType("Brave.Gameplay.Run.RunController");
        if (controllerType == null)
        {
            Debug.LogWarning("[SceneSetup] RunController type not found — skipping.");
            return;
        }

        var go = new GameObject("[Run]");
        var comp = go.AddComponent(controllerType);
        var so = new SerializedObject(comp);

        // Wire CharacterDefinition (Bunny) — same asset as PlayerMover.
        var charDef = AssetDatabase.LoadAssetAtPath<CharacterDefinition>(CharBunnyAssetPath);
        if (charDef == null)
        {
            Debug.LogWarning(
                "[SceneSetup] RunController: Char_bunny.asset not found — "
                + "run 'Brave > Generate Balance SOs from JSON' first.");
        }
        var charProp = so.FindProperty("_activeCharacter");
        if (charProp != null)
            charProp.objectReferenceValue = charDef;

        // _activeBiome and _deathChannel remain null — graceful degradation.
        // RunController.Update only ticks when State == Running; it will skip until
        // Initialise() is called at play-mode boot.

        so.ApplyModifiedPropertiesWithoutUndo();
        Debug.Log("[SceneSetup] [Run] / RunController wired.");
    }

    /// <summary>
    /// Creates [HUD] GameObject with:
    ///   - UIDocument component with RunHud.uxml panel-settings-asset assigned
    ///   - RunHudController component (which requires UIDocument via [RequireComponent])
    /// The HUD will render placeholder stub values via RunHudStubRuntime until
    /// IRunRuntimeState is wired by gameplay-engineer in a future dispatch.
    /// </summary>
    private static void EnsureRunHud()
    {
        var hudType = FindType("Brave.UI.Controllers.RunHudController");
        if (hudType == null)
        {
            Debug.LogWarning("[SceneSetup] RunHudController type not found — skipping HUD.");
            return;
        }

        var go = new GameObject("[HUD]");

        // UIDocument is required by RunHudController ([RequireComponent]).
        // AddComponent order matters: UIDocument first, then RunHudController.
        var uiDocType = FindType("UnityEngine.UIElements.UIDocument");
        Component? uiDoc = null;
        if (uiDocType != null)
        {
            uiDoc = go.AddComponent(uiDocType);
            // Assign the RunHud.uxml VisualTreeAsset to the UIDocument.
            var vtAsset = AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(RunHudUxmlPath);
            if (vtAsset == null)
            {
                Debug.LogWarning(
                    $"[SceneSetup] RunHud.uxml not found at {RunHudUxmlPath} — "
                    + "UIDocument will have no panel content until the UXML is assigned manually.");
            }
            else
            {
                var docSo = new SerializedObject(uiDoc);
                var vtProp = docSo.FindProperty("m_VisualTreeAsset");
                if (vtProp != null)
                {
                    vtProp.objectReferenceValue = vtAsset;
                    docSo.ApplyModifiedPropertiesWithoutUndo();
                }
            }
        }
        else
        {
            Debug.LogWarning("[SceneSetup] UIDocument type not found — HUD may not render.");
        }

        go.AddComponent(hudType);
        Debug.Log("[SceneSetup] [HUD] / RunHudController wired.");
    }

    /// <summary>
    /// Adds the canonical <see cref="PlayerMover"/> to the Run-scene Player GameObject
    /// and assigns its <c>character</c> field to the Bunny CharacterDefinition SO.
    /// Idempotent — re-running the scaffold does not stack duplicate components.
    /// Assumes <c>Brave > Generate Balance SOs from JSON</c> has already produced the SO;
    /// if it hasn't, the asset lookup logs a warning and the component is added
    /// un-configured (PlayerMover.Awake will then disable itself with a clear error).
    /// </summary>
    private static void EnsureRunPlayerWiring(GameObject player)
    {
        var mover = player.GetComponent<PlayerMover>() ?? player.AddComponent<PlayerMover>();

        var charDef = AssetDatabase.LoadAssetAtPath<CharacterDefinition>(CharBunnyAssetPath);
        if (charDef == null)
        {
            Debug.LogWarning(
                $"[SceneSetup] {CharBunnyAssetPath} not found — run 'Brave > Generate Balance SOs from JSON' "
                + "before launching Play mode so PlayerMover can resolve its move-speed.");
            return;
        }

        // Use SerializedObject so the private [SerializeField] survives scene-save without
        // requiring a public setter on PlayerMover (which would loosen its API contract).
        var so = new SerializedObject(mover);
        var prop = so.FindProperty("character");
        if (prop != null)
        {
            prop.objectReferenceValue = charDef;
            so.ApplyModifiedPropertiesWithoutUndo();
        }
        else
        {
            Debug.LogWarning("[SceneSetup] PlayerMover.character SerializedProperty not found — "
                + "field may have been renamed; update CharBunnyAssetPath wiring accordingly.");
        }
    }

    private static void EnsureMainMenu()
    {
        var path = $"{SceneDir}/MainMenu.unity";
        if (File.Exists(path)) { Debug.Log("[SceneSetup] MainMenu.unity already exists, skipping"); return; }
        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        var cam = new GameObject("MainCamera");
        var camera = cam.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = new Color(1f, 0.92f, 0.76f);   // bunny-cream
        cam.tag = "MainCamera";
        cam.AddComponent<AudioListener>();
        var eventSystem = new GameObject("EventSystem");
        var esType = FindType("UnityEngine.EventSystems.EventSystem");
        if (esType != null) eventSystem.AddComponent(esType);

        // Wave 7B — wire HomeController + Home.uxml so the MainMenu scene actually shows
        // a Home screen on launch. Idempotent — re-running the scaffold leaves the
        // existing GameObject + components intact.
        RunSceneWiringSetup.EnsureHomeControllerWithUxml();

        EditorSceneManager.SaveScene(scene, path);
        Debug.Log($"[SceneSetup] created {path}");
    }

    private static void EnsureLoadout()
    {
        var path = $"{SceneDir}/Loadout.unity";
        if (File.Exists(path)) { Debug.Log("[SceneSetup] Loadout.unity already exists, skipping"); return; }
        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        var cam = new GameObject("MainCamera");
        var camera = cam.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = new Color(0.74f, 0.88f, 0.45f); // meadow-lime
        cam.tag = "MainCamera";
        cam.AddComponent<AudioListener>();
        var eventSystem = new GameObject("EventSystem");
        var esType = FindType("UnityEngine.EventSystems.EventSystem");
        if (esType != null) eventSystem.AddComponent(esType);

        // Wave 7B — LoadoutController + Loadout.uxml lets the player pick a character
        // before the Run scene loads.
        RunSceneWiringSetup.EnsureLoadoutControllerWithUxml();

        EditorSceneManager.SaveScene(scene, path);
        Debug.Log($"[SceneSetup] created {path}");
    }

    private static void EnsurePerfStress()
    {
        var path = $"{SceneDir}/PerfStress.unity";
        if (File.Exists(path)) { Debug.Log("[SceneSetup] PerfStress.unity already exists, skipping"); return; }

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var cam = new GameObject("MainCamera");
        var camera = cam.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = Color.black;
        cam.transform.position = new Vector3(0, 30, -20);
        cam.transform.rotation = Quaternion.Euler(55, 0, 0);
        cam.tag = "MainCamera";
        cam.AddComponent<AudioListener>();

        // Attach FpsSampler so PerfStressFpsTest can read AverageFps without a separate
        // populator pass. Resolved by name to avoid a hard reference from this Editor
        // script to the Brave.Diagnostics asmdef.
        var fpsType = FindType("Brave.Diagnostics.FpsSampler");
        if (fpsType != null)
        {
            cam.AddComponent(fpsType);
        }
        else
        {
            Debug.LogWarning("[SceneSetup] Brave.Diagnostics.FpsSampler not resolved — PerfStress scene missing FpsSampler.");
        }

        // Light so things render in screenshots.
        var light = new GameObject("DirectionalLight");
        light.AddComponent<Light>().type = LightType.Directional;
        light.transform.rotation = Quaternion.Euler(60, 0, 0);

        EditorSceneManager.SaveScene(scene, path);
        Debug.Log($"[SceneSetup] created {path}");
    }

    private static void RegisterInBuildSettings()
    {
        // Force AssetDatabase to re-import any freshly-created .unity files so their
        // GUIDs are queryable below (fixes the ForceScaffold case where the old
        // EditorBuildSettings entry had a stale all-zero GUID).
        AssetDatabase.Refresh();

        var canonical = new[] {
            $"{SceneDir}/Boot.unity",
            $"{SceneDir}/MainMenu.unity",
            $"{SceneDir}/Loadout.unity",
            $"{SceneDir}/Run.unity",
            $"{SceneDir}/PerfStress.unity"
        };

        // Start from existing list so any author-added scenes survive, but replace
        // entries for our canonical paths so their GUIDs match the current asset.
        var existing = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
        var canonicalSet = new HashSet<string>(canonical);
        existing.RemoveAll(s => canonicalSet.Contains(s.path));

        foreach (var p in canonical)
        {
            if (!File.Exists(p)) continue;
            existing.Add(new EditorBuildSettingsScene(p, enabled: true));
        }
        EditorBuildSettings.scenes = existing.ToArray();
        Debug.Log($"[SceneSetup] EditorBuildSettings.scenes now: {EditorBuildSettings.scenes.Length}");
    }

    private static Type FindType(string fullName)
    {
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            var t = asm.GetType(fullName, throwOnError: false);
            if (t != null) return t;
        }
        return null!;
    }
}
#endif
