name: bb-debug-if-simple

on:
  push:
    branches: [debug/bb-workflows]
    paths:
      - '.github/workflows/bb-debug-if-simple.yml'

jobs:
  hello:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - run: echo "simple if-guard works"
