name: bb-debug-defaults

on:
  push:
    branches: [debug/bb-workflows]
    paths:
      - '.github/workflows/bb-debug-defaults.yml'

jobs:
  hello:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: games/brave-bunny/app
    steps:
      - uses: actions/checkout@v4
      - run: pwd && ls
